# syntax=docker/dockerfile:1

FROM node:22-alpine
WORKDIR /app/API

COPY API/package*.json ./
RUN npm ci --omit=dev

COPY API ./                         
COPY src/ScoringConfigs /app/src/ScoringConfigs

EXPOSE 8080

CMD ["node", "/app/API/config/server.js"]